# Generated by Django 5.0.7 on 2024-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
