# Generated by Django 5.0.7 on 2024-08-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_restaurant_price_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('representative', models.CharField(max_length=255)),
                ('established_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
